version: 2

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/morethancertified/mtc-cli/cmd.Version={{.Version}}
archives:
  - format: binary
# brews:
#   - tap:
#     owner: morethancertified
#     name: mtc-cli-tap 
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
